[package]
name = "fedimint-leptos-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'

[dependencies]
async-trait = "0.1.68"
anyhow = "1.0.71"
base64 = "0.21.3"
fedimint-client = { git = "https://github.com/fedimint/fedimint", rev = "480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357" }
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357" }
fedimint-wallet-client = { git = "https://github.com/fedimint/fedimint", rev = "480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357" }
fedimint-mint-client = { git = "https://github.com/fedimint/fedimint", rev = "480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357" }
fedimint-ln-client = { git = "https://github.com/fedimint/fedimint", rev = "480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357" }
futures = "0.3.28"
hex = "0.4.3"
leptos = { version = "0.4.8", features = ["csr"] }
leptos-qr-scanner = { git = "https://github.com/elsirion/leptos-qr-scanner", rev = "75e976e99d9c1ed64921081a23f7da823d2a0b6d" }
leptos_icons = { version = "0.0.15", features = ["macros", "BsLightningCharge", "FaCoinsSolid"] }
leptos_meta = { version = "0.4.8", features = ["csr"] }
lightning-invoice = { version = "0.21.0", features = [ "serde" ] }
qrcode-generator = "4.1.8"

console_error_panic_hook = "0.1.7"
tracing = "0.1.37"
tracing-wasm = "0.2.1"

thiserror = "1.0"

serde = { version = "1.0", features = ["derive"] }

tokio = { version = "1.28.2", features = [ "rt", "sync", "time" ] }
tokio-stream = "0.1.14"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"

rexie = "0.4.2"

[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }
ring = { git = "https://github.com/dpc/ring", rev = "5493e7e76d0d8fb1d3cbb0be9c4944700741b802" }
