name: Build App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Publish app
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: fedimint
          skipPush: true
        continue-on-error: true

      - uses: Swatinem/rust-cache@v2

      - name: Build app
        run: nix develop --command bash -c 'npm i && trunk build --release'

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: webimint.sirion.io
